
POST http://localhost:8000/system_api/generate-api/
Content-Type: application/json

{
  "file": "makegame",
  "format": [
    {
      "id": "Input_1725866871043",
	  "type":"Input",
      "structure": {
        "username": {
          "fields": [
            {
              "target": "Output_1725866867893",
              "location": "email"
            }
          ]
        },
        "password": {
          "fields": [
            {
              "target": "Output_1725866867893",
              "location": "password"
            }
          ]
        }
      }
    },
    {
      "id": "Output_1725866867893",
	  "type":"Output",
      "structure": {
        "email": {
          "fields": [
            {
              "target": "none",
              "location": "none"
            }
          ]
        },
        "password": {
          "fields": [
            {
              "target": "none",
              "location": "none"
            }
          ]
        }
      }
    }
  ]
}

